language: cpp

branches:
  only:
   - master

addons:
  apt:
    packages:
      - lcov
      - doxygen

os:
  - linux

compiler:
  - gcc
  - clang

notifications:
  email:
    on_success: never
    on_failure: always

script:
  - cmake CMakeLists.txt
  - make
  - ctest

after_success:
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
